Clippy Cleanup
Polkadex-Substrate/polkadexTEE-worker pull request #185
Opened 2021-07-07 19:19 UTC by arrudagates

Lots of clippy warnings got through unnoticed before, this PR aims to clean all of them.

2021-07-07 19:21 UTC, arrudagates commented
Should close issue #179 and allow PR #180 to pass CI

2021-07-07 19:34 UTC, arrudagates commented
Had to allow clippy warnings to be ignored in some places like here (https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/a2807272558f0ce0c9eb9c2a5ab7cded963618c7/enclave/src/polkadex_cache/cancel_order_cache.rs#L72), because that type comes from outside the enclave.

2021-07-12 07:08 UTC, haerdib requested changes
LGTM, only one change request.

And maybe an additional request, but I'll leave it up to you if you want to do it or not  (because that might introduce too many changes that may break some rebase):
Since you're already introducing many cargo fmt changes in the enclave, maybe you could also do so in the worker (run cargo fmt once inside the enclave folder and once outside of the enclave folder).

2021-07-12 07:08 UTC, haerdib commented on enclave/src/top_pool/pool.rs
> +            .flatten()
This will not do the right thing. Even though we don't use the pool in polkadex, I don't think we should introduce errors.
You can just copy paste from here:
https://github.com/integritee-network/worker/blob/c0d1885acf84893dd0c5551795afc6efa8726c3c/enclave/src/top_pool/pool.rs#L250-L256

2021-07-12 13:16 UTC, arrudagates commented
This PR should be closed as soon as the change requested is implemented and a rebase from develop is done, which should check for the CI implemented in PR #180

2021-07-14 09:52 UTC, zktony commented
@arrudagates checks are failing .. there are still some issues in formatting.

2021-07-14 11:18 UTC, zktony approved these changes

2021-07-14 12:34 UTC, haerdib approved these changes
LGTM, thanks!

2021-07-14 12:35 UTC, arrudagates commented
Great, can we merge this PR?

2021-07-14 12:38 UTC, merged