Edit Order RPC
Polkadex-Substrate/polkadexTEE-worker pull request #313
Opened 2021-10-27 12:42 UTC by arrudagates

This PR implements the Edit Order RPC endpoint by means of removing the order and replacing the edited version. Closes #259

2021-10-28 10:03 UTC, haerdib requested changes
This function is not yet callable from a client. Please also add a cli function as well as add it to the rpc interface like here: https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/enclave/src/rpc/worker_api_direct.rs#L140-L148

2021-10-28 10:03 UTC, haerdib commented on enclave/src/polkadex_orderbook_storage.rs
> +    // TODO: Handle this unwrap
Is this TODO still up to date?

2021-10-28 10:03 UTC, haerdib commented on stf/src/lib.rs
> +    edit_order(AccountId, EditOrder, Option<AccountId>),
Can you add comments here what each types signifies (just like for the other calls?)

2021-10-28 10:03 UTC, haerdib commented on enclave/src/rpc/rpc_edit_order.rs
> +        test: bool,
I don't think we should add testing variable to a function used in production.

If you want to avoid to call the orderbook storage, it would be better to implement a Mock struct for the orderbook storage, so the code in this function stays the same, wether it's for testing purpose or for production mode.

2021-10-28 10:03 UTC, haerdib commented on enclave/src/rpc/rpc_edit_order.rs
> +        test: bool,
Just like its done for the rpc gateway

2021-10-28 10:03 UTC, haerdib commented on polkadex-primitives/src/types.rs
> +    pub fn from_order(order: Order, order_id: OrderUUID) -> Self {
What does this function do? please add a more descriptive name and/or some comments

2022-02-10 01:57 UTC, simonsso commented
obsolete

2022-02-10 01:57 UTC, closed without merging