Resolved all conflcits
Polkadex-Substrate/polkadexTEE-worker pull request #48
Opened 2021-05-17 10:24 UTC by ksr30

2021-05-17 12:11 UTC, haerdib requested changes
Minor issues, otherwise it does look good to me

2021-05-17 12:11 UTC, haerdib commented on enclave/src/lib.rs
> +                    Ok(()) => execute_ocex_release_extrinsic(main_acc.clone(), token, amount, 0), // TODO: How to get nonce?
I've written down my thought in issue #12

2021-05-17 12:11 UTC, haerdib commented on enclave/src/lib.rs
> +        genesis_hash, // FIXME: Shouldn't this be the latest head?
@brenzi do you know the answer to this question or should I look into it?

2021-05-17 12:11 UTC, haerdib commented on enclave/src/polkadex_balance_storage.rs
> +pub fn deposit(main_acc: AccountId, token: AssetId, amt: u128) -> SgxResult<()> {
Proposal: rename function to lock_storage_and_deposit or aquire_lock_and_deposit or something similiar

2021-05-17 12:11 UTC, haerdib commented on enclave/src/polkadex_balance_storage.rs
> +pub fn withdraw(main_acc: AccountId, token: AssetId, amt: u128) -> SgxResult<()> {
Proposal: rename function to lock_storage_and_deposit or aquire_lock_and_deposit or something similiar (could also be load_storage_and_desposit, as long as the additonial steps are named)

2021-05-17 12:11 UTC, haerdib commented on enclave/src/polkadex_balance_storage.rs
> +pub fn get_balances(main_acc: AccountId, token: AssetId) -> SgxResult<Balances> {
same as the two above

2021-05-17 12:11 UTC, haerdib commented on enclave/src/test_polkadex_balance_storage.rs
> +    {
I think those curly brackets are unnecessary left overs and are a little bit confusing.. or are they actually necessary?

2021-05-17 12:11 UTC, haerdib commented on enclave/src/test_polkadex_balance_storage.rs
> +    {
Same as above

2021-05-17 12:45 UTC, ksr30 commented on enclave/src/test_polkadex_balance_storage.rs
> +    {
done

2021-05-17 12:45 UTC, ksr30 commented on enclave/src/test_polkadex_balance_storage.rs
> +    {
done

2021-05-17 12:50 UTC, ksr30 commented on enclave/src/polkadex_balance_storage.rs
> +pub fn withdraw(main_acc: AccountId, token: AssetId, amt: u128) -> SgxResult<()> {
done

2021-05-17 12:50 UTC, ksr30 commented on enclave/src/polkadex_balance_storage.rs
> +pub fn deposit(main_acc: AccountId, token: AssetId, amt: u128) -> SgxResult<()> {
done

2021-05-17 12:50 UTC, ksr30 commented on enclave/src/polkadex_balance_storage.rs
> +pub fn get_balances(main_acc: AccountId, token: AssetId) -> SgxResult<Balances> {
done

2021-05-17 12:54 UTC, Gauthamastro commented on enclave/src/lib.rs
> +                    Ok(()) => execute_ocex_release_extrinsic(main_acc.clone(), token, amount, 0), // TODO: How to get nonce?
Sure

2021-05-17 12:55 UTC, Gauthamastro commented on enclave/src/lib.rs
> +                    Ok(()) => execute_ocex_release_extrinsic(main_acc.clone(), token, amount, 0), // TODO: How to get nonce?
We will fix this in a separate issue

2021-05-17 13:13 UTC, Gauthamastro commented on enclave/src/lib.rs
> +        genesis_hash, // FIXME: Shouldn't this be the latest head?
Moving it separate issue.

2021-05-17 13:15 UTC, Gauthamastro approved these changes

2021-05-17 13:21 UTC, haerdib approved these changes
LGTM

2021-05-17 13:26 UTC, merged

2021-05-21 13:22 UTC, brenzi commented on enclave/src/lib.rs
> +        genesis_hash, // FIXME: Shouldn't this be the latest head?
I believe this only makes a difference when lifetime isn't `immortal`. There is actually an issue in the api-client 
https://github.com/scs/substrate-api-client/issues/108
that would need to be resolved first, so, for now, genesis is fine